<?php
// echo "<pre>";
// print_r($albums);
// echo "</pre>";
?>


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Albums</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/dd3ee9631d.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="./css/style.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abel|Inter">
</head>

<body>
    <div class="container wrapper" >
        <h1 class="title text-center mt-5">Boom</h1>
        <a href="/?action=addForm" title="Ajouter un nouvel album" class="add-btn link-underline link-underline-opacity-0 d-flex justify-content-center align-items-center"> 
            <span class="add-icon fas fa-plus-circle text-center"></span> 
        </a>
      <?php if (count($albums) > 0): ?>
        <div id="liveToast" class="toast bg-success text-white position-fixed top-0 end-0" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-body position-relative">Album créé avec succès
                <span type="button" class="fas fa-times fs-5 position-absolute bottom-25 end-0 px-2" data-bs-dismiss="toast" arial-label="Close"></span>
            </div>
        </div>
        <button id="toast" class="btn btn-primary">Toast</button>
        <div class="container mt-5">
            <div class="row row-gap-4">
                <?php foreach ($albums as $album) : ?>
                    <!-- A générer dynamiquement -->
                    <div class="col col-3">
                    <div class="card rounded shadow border border-0">
                        <img src="./assets/App-picture.png" alt="" class="card-img-top">
                        <div class="card-body">
                            <h4 class="card-title"><?= $album['title'] ?></h4>
                            <h5 class="card-subtitle text-body-secondary"><?= $album['artist'] ?></h4>
                            <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. At id, quidem ut ducimus nobis aspernatur</p>
                            <a class="card-link btn btn-success " href="/?action=editForm&id=<?= $album['id'] ?>"><span class="fas fa-edit"></span></a>
                            <a class="card-link btn btn-danger " href="/delete?id=<?= $album['id'] ?>"><span class="fas fa-trash-alt"></span></a>
                        </div>
                    </div>
                    </div>
                    </li>
                <?php endforeach; ?>
            </div>
        </div>
      <?php else:?>
        <p> Pas d'albums </p>
      <?php endif;?>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script>
        let btn = document.querySelector("#toast");
        let toast = document.querySelector("#liveToast");

        const liveToast = bootstrap.Toast.getOrCreateInstance(toast);
        btn.addEventListener("click", ()=> {
            liveToast.show();
        })
    </script>
</body>

</html>